# Generated by Django 5.1.7 on 2025-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_assignment_student_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="marks",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
